---
- name: Start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Adjust Firewall
  shell: "firewall-cmd --permanent --zone=public --add-port=8080/tcp && firewall-cmd --reload"
